### ISSUE TITLE
Uncaught ReferenceError: AwesompleteUtil is not defined

### ISSUE THREAD

**Issue by mbaleczny** [nico-amsterdam/phoenix_form_awesomplete#1]
Hi

I'm trying to use this library in my project. I've used example from README, but error occures in browser console:  `Uncaught ReferenceError: AwesompleteUtil is not defined` with linked line of code:
`<input class="form-control" id="user_country" name="user[country]" type="text"><script>AwesompleteUtil.start('#user_country', {url: 'https://restcountries.eu/rest/v1/all', loadall: true, prepop: true}, {minChars: 1, maxItems: 8, data: function(rec, input) { return rec['name']; }});</script>...`

I've added JavaScript files `awesomeplete.min.js` and `awesomplete-util.min.js` with use of brunch. Files are listed in sources. After running command `Awesomeplete.start...` widget is working.

Any idead what's wrong?

Thanks!

**Comment by nico-amsterdam** [comment]
Locate your app.html.eex file. Did you add these lines? :


`<link rel="stylesheet" href="//nico-amsterdam.github.io/awesomplete-util/css/awesomplete.css">`
`<script src="//nico-amsterdam.github.io/awesomplete-util/js/awesomplete.min.js"></script>`
`<script src="//nico-amsterdam.github.io/awesomplete-util/js/awesomplete-util.min.js"></script>`
`<style>`
`  div.awesomplete {display: block}`
`  div.awesomplete ul li p {display: block; font-size: small; margin-left: 1em}`
`  div.awesomplete .awe-found {border: 2px solid green}`
`  .hide-not-found div.awesomplete .awe-not-found {border-color: lightblue}`
`  div.awesomplete .awe-not-found {border: 2px solid red}`
`</style>`

**Comment by mbaleczny** [comment]
I've found out what was wrong. These lines should be above ```<body></body>```, but were below instead.

Stupid mistake. Please, have in mind that I am newbie in web development :wink: 
Thanks!
