### ISSUE TITLE
Unable to load phoenix_form_awesomplete JS

### ISSUE THREAD

**Issue by mudspot** [nico-amsterdam/phoenix_form_awesomplete#7]
Hi!

*Version*
PhoenixFormAwesomplete 0.3.2
Elixir/Erlang - 1.16-OTP26
Phoenix 1.7.12

*Description*
I followed the instruction at https://hexdocs.pm/phoenix_form_awesomplete/PhoenixFormAwesomplete.html#module-installation

I added `import { AwesompleteUtil, attachAwesomplete, copyValueToId } from "phoenix_form_awesomplete"` to my `assets/js/app.js`.

The following error is thrown
`✘ [ERROR] Could not resolve "phoenix_form_awesomplete"

js/app.js:29:66:
29 │ ...attachAwesomplete, copyValueToId } from "phoenix_form_awesomplete"
╵                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

You can mark the path "phoenix_form_awesomplete" as external to exclude it from the bundle, which will remove this error.`

Best regards
Terry

**Comment by nico-amsterdam** [comment]
Thanks Terry, I see it.

The package.json is missing in the hex distribution.

I will look how to fix this.

**Comment by nico-amsterdam** [comment]
Terry,

Version 0.3.3 is available in hex, which includes the package.json to solve your the issue
Run:
    mix deps.update phoenix_form_awesomplete

to get the latest version

**Comment by LameckMeshack** [comment]
Hello @nico-amsterdam I am still getting error in version 1.0.0

**Comment by nico-amsterdam** [comment]
> Hello @nico-amsterdam I am still getting error in version 1.0.0
@LameckMeshack   In your project, what is the output of:
`mix deps --all`

After changing mix.exs, did you run this?

`mix deps.update phoenix_form_awesomplete`

**Comment by ashrafhasson** [comment]
I see this issue with a fresh install of version 1.0.2. Should we request re-opening this issue or create a new one?

**Comment by ashrafhasson** [comment]
It turns out that I had removed parts of the `esbuild` system and it was no longer pulling in phoenix_form_awesomplete and building its assets into the app's assets. I had to reset `esbuild` to get it to work properly again.

**Comment by nico-amsterdam** [comment]
Good that you could solve this with perseverance.
I didn't know it was possible to remove parts of esbuild, since the Phoenix package itself also has assets to be assembled in the app by esbuild.

**Comment by ashrafhasson** [comment]
Yeah, it wasn't obvious what exactly is breaking that but it was clear it wasn't pulling in phoenix_form_awesomplete. I had left the `build.js` script there along with a mix task that references it and trusted that it was enough to pull in the necessary addons .. I had removed `:esbuild` earlier in favor of `tailwind` and I must've borked something. 
Thanks for your response though.

Update: it turned out that the `esbuild` options were missing the `nodePath: ["../deps"]` setting!
